services:
  symfony_bunq.commands.callback_url:
    class: Jorijn\SymfonyBunqBundle\Command\CallbackUrlCommand
    arguments:
      - 'bunq:callback-url'
      - '@symfony_bunq.component.command.api_helper'
      - "@router"
    tags:
      - { name: 'console.command' }

  symfony_bunq.commands.list_accounts:
    class: Jorijn\SymfonyBunqBundle\Command\ListAccountsCommand
    arguments:
      - 'bunq:list-accounts'
      - '@symfony_bunq.component.command.api_helper'
    tags:
      - { name: 'console.command' }

  symfony_bunq.commands.initialize_bunq:
    class: Jorijn\SymfonyBunqBundle\Command\InitializeBunqApiCommand
    arguments:
      - 'bunq:initialize'
      - '@symfony_bunq.component.command.api_helper'
      - '%bunq.environment%'
      - '%bunq.configuration_file%'
      - '%bunq.application_description%'
      - '%bunq.allowed_ips%'
    tags:
      - { name: 'console.command' }

  symfony_bunq.commands.list_current_user:
    class: Jorijn\SymfonyBunqBundle\Command\ListCurrentUserCommand
    arguments:
      - 'bunq:current-user'
      - '@symfony_bunq.component.command.api_helper'
    tags:
      - { name: 'console.command' }

  symfony_bunq.component.command.api_helper:
    class: Jorijn\SymfonyBunqBundle\Component\Command\ApiHelper
    arguments:
      - '%bunq.configuration_file%'
      - '@symfony_bunq.component.crypt.aes_256_cbc'

  symfony_bunq.component.crypt.aes_256_cbc:
    class: Jorijn\SymfonyBunqBundle\Component\CryptAes256Cbc